#Nom de la composition
name: devops

#Décrire tous les containers qu'on y met : services
services:
  #service 1 : notre application
  app:
    image: app-devops:1.0
    ports:
      - 9501:8000
    networks:
      - devopsc
    volumes:
      - "./.env:/app/.env"

    #Préciser d'autres options
    #environment
    #etc.

  db:
    image: postgres
    ports:
      - 54321:5432
    environment:
      - "POSTGRES_PASSWORD=mysecretpassword"
      - "POSTGRES_DB=devopsc"
    networks:
      - devopsc
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data 

volumes:
  postgres-data:

networks:
  devopsc: